require 'dig'

class ShortenLandlordsNotes < ActiveRecord::Migration
  def self.up
    self.name_notes.each do |name_note|
      if dig = Dig.find_by_name(name_note[:name])
        dig.update_attribute(:landlords_notes, name_note[:notes][0...140])
      end
    end
  end

  def self.down
  end
  
private
  def self.name_notes
    thing = [
    {:name => "Attn Nick, Dream House", :notes => "2x1 bed/2x2 bed apartments.TV/CD/ADSL/wm/dryer, quiet 5*. Buses to Festival & King's Theatres."},
    {:name => "Berlitz Edinburgh", :notes => "L-shaped kitchen/dining area & living room, 2nd bedroom with two bunk beds (suitable for children, teenages & small adults), bathroom with bath tub & shower over bath, allocated secure car park, access to south facing hillside garden. Double sofa for occasional guests, TV, wm, td, iron & board. mw,  kitchen amenities. Rental from Sat or Sun to Sun. Longer rentals if needed."},
    {:name => "Broughton Property Management", :notes => "Fully furnished attractive 2nd floor flat available very close to Playhouse Theatre. This accommodation is one double bedroom, one smaller bedroom with double bed & 1 single bed in boxroom. Bright sitting room, large kitchen with dining area. Available from July 7th until August 23rd."},
    {:name => "Canon Court Luxury Serviced Apartments", :notes => "Many features. Not far from theatre, also on bus route. "},
    {:name => "Crichton-Stuart Management Services Ltd.", :notes => "Various Properties to let. All very reasonable rates. "},
    {:name => "Destination Edinburgh Apartments", :notes => "1 & 2 bed Apartments. "},
    {:name => "Destination Edinburgh Apartments", :notes => "1, 2 & e Bed Apartments available. Bus to Festival Theatre"},
    {:name => "Edinburgh Flats", :notes => "We operate a number of self catering apartments in the City Centre, one of which on Windsor Street is ideally situated for the Playhouse. I can be contacted either by email or phone or website. Please do not hesitate to contact me. "},
    {:name => "Factotum - Susanna Thomson", :notes => "GCH with all local amenities. Lounge (widescreen TV, DVD, video) dining room, kitchen, bathroom (bath with shower). Rent: 1 week to 5 months £900 per month) Bus to King's Theatre"},
    {:name => "Factotum Property Services", :notes => "Long & short term lets. "},
    {:name => "Festival Flats", :notes => "www.festival flats.net, 1, 2, 3 & 4 bed properties"},
    {:name => "Fountain Court Apartments", :notes => "1 & 2 bedroom apartments. Secure Parking - Contact: Marie Neil, General Manager.Bus to Festival Theatre."},
    {:name => "Garry Forbes", :notes => "TV/CH/CD/Parking, Serviced Flats. Bus to Kings's Theatre"},
    {:name => "Glenalmond Guest House", :notes => "All bedrooms fully ensuite & tea & coffee facilities. Full CH, TV lounge, own keys and 24 hr access. "},
    {:name => "Holyrood Aparthotel, Blair Wallace", :notes => "based on 2 sha full kit/ph/ISDN/direct dial, gym,secure car park/TV/S 10 min walk to Festival Theatre"},
    {:name => "Inverleith Hotel", :notes => "Spacious 1st floor flat featuring large drawing room with 3 windows. 2 double bedrooms (1 with double and single beds & 1 with a double bed). There is also a sofa bed. Close to City Centre & Playhouse Theatre. Situated in a leafy & desirable New Town area. Very close to Tesco, Royal Botanic Gardens, Water of Leith & Stockbridge. "},
    {:name => "John & Cathy McCaffety", :notes => "Georgian Villa, walled garden, very private. 2 family rooms, use of bathroom, Vegetarian breakfast."},
    {:name => "John & Donna Hand", :notes => "All rooms are full ensuite & include refreshments & TV with video. Clean & efficient service. Extension choice of Scottish & Continental b'fast."},
    {:name => "Lochend Serviced Apartments", :notes => "42 x 1 & 2 bedroom serviced flats. TV/DVD/CD. Tel/Parking. Buses to Festival & King's Theatres.  "},
    {:name => "Lochend Serviced Apartments", :notes => "Lochend Serviced Apartments are a complex of exclusive serviced apartments. Located in a stylish modern development in the trendy Western Harbour, 1.6 miles from the city centre and 10 mins. away from the heart of the city enabling easy access to everything Edinburgh has to offer. Provides a first class service ensuring you have all you need during your stay from transport, free business facilities access & groceries delivered to your apartment door, to help with arranging leisure activities. Each contemporary style apartment benefits from a fully equipped kitchen with modern appliances as well as satellite TV, phone & ensuite facilities. "},
    {:name => "Marie Neil, General Manager", :notes => "1 or 2 bedroom apartments.Secure parking. Bus to Festival Theatre. "},
    {:name => "Mark McLeod, Clouds Accom. Agency", :notes => "A selection of superb, self catering apartments all close to theatres. Sizes range from 1 bedroom to 4 bedroom. "},
    {:name => "Mary McIntosh", :notes => "Twin & Double rooms with TV, tea/coffee making facilities also lounge/dining area for guests. Cont. b'fast. Special rates for longer term guests."},
    {:name => "Morrison Bishop Letting", :notes => "Various Flats Available. "},
    {:name => "Mrs Anne White", :notes => "Guest House - 4 rooms. £23.00 pn for bed and full Scottish b'fast becomes £20.00 after 3 nights. (Prices may change in high season)."},
    {:name => "Mrs Izzy McHendry", :notes => "All rooms have shower, wash basin, colour TV & kettle. Smoking permitted. 5 mins. walk Town Centre. (Backpackers only)"},
    {:name => "Oakhill Apartments Ltd.", :notes => "2009 has been an exciting year for Oakhill Apartments Ltd which we're rounding off with a launch of our redesigned website which has some fantastic new features including details of our new serviced apartments in Edinburgh City Centre. You can book online, view even more photographs in our new gallery and find out more about the excellent service we offer. Log on now to further explore the benefits of staying at Oakhill Apartments. We also have an Oakhill DVD coming soon to give an even better flavour of what we have on offer, so please look out for that. In the meantime, if you like what you see, please contact the team with any enquiries you may have. We look forward to welcoming you to Oakhill Apartments very soon........."},
    {:name => "Pilrig House Apartments", :notes => "Pilrig House is an historic Scottish townhouse (built 1638) with three wonderfully comfortable & superbly equipped 4 star graded apartments. Uniquely located on the edge of a tranquil park yet only a short stroll (5 mins. by bus) to Edinburgh's City Centre and a 10 min. walk to The Playhouse. Pilrig House has a fascinating history and a remarkable literary connection. It was the home of Robert Louis Stevenson's family. Guests can enjoy tranquillity, panoramic park views, free parking in a private car park, Broadband Wi-Fi internet access, exceptional facilities, fine bedlinen, fluffy towels/robes, luxury Scottish toiletries, plus many other delightful extras and a warm welcome from the owners, Debbie & Philip. "},
    {:name => "Secret Edinburgh", :notes => "Four bedrooms, equipped modern kitchen, Broadband connection. Bus to Festival Theatre. "},
    {:name => "Springfield Luxury Apartments", :notes => "Fully serviced 3 bedroom apartments situated 5 mins. by bus from Princess Street & 5 mins. from Ocean and The Shore - vibrant restaurant community. 3 dbl bedrooms, 2 bathrooms & showers, 1 ensuite, fitted kitchen, fully equipped lounge. Pvt development in block of 3, suitable for 4 couples or 6 professionals. Flat has own door entrance, reception area, fully equipped lounge with satellite TV access, fully fitted kitchen with wd, dw, integrated cooker, ff, bathroom with shower & Jacuzzi, separate ensuite, wireless Internet access is provided free of charge (laptop required). Free weekly servicing including linen changing and cleaning. The apartment is conveniently located for major Edinburgh attractions, theatres, botanic gardens, Omni centre, Princess Street, Edinburgh tours etc."},
    {:name => "The Club, Jewel & Esk College", :notes => "104 Sgl/Twin rooms (shared facilities). TV/Lounges/vending/b'fast at Club/mw/fridge.Buses/Trains to Festival & King's Theatres."},
    {:name => "The Greenhouse (Guest House)", :notes => "Wide choice of accommodation. Tariffs depend on time of year.Completely Vegetarian & No smoking. "},
    {:name => "Urban Dream Properties", :notes => "5th Floor, 2dbls (1 ensuite) Lge/Din/Kit, GCH, Parking & Balcony. Buses to Festival & King's Theatres"},
    {:name => "Waterfront Apartments", :notes => "25 (2 & 3 bed) Apartments all fully fitted and equipped. Buses to Festival & King's Theatres"},
    {:name => "Alan Chalmers", :notes => "3 bed apartment, sitting room, dining-room, kitchen & bathroom. Laundry. Maid. Use of restaurant (cost extra), lift. Short or Long Term Lease. "},
    {:name => "Alan Chambers", :notes => "3 bed apartment, sitting room/dining rm, kitchen & bathroom.Laundry Maid.Lift, car parking. £1,100 pm exl. Phone. Use of Restaurant (cost extra)( £150pm) for car parking & short or long term lease not included - no room."},
    {:name => "Caroline & Mark McCraw", :notes => "Ground flr.main door flat. Fitted kit/Liv/Rm/Bath/Sh, GCH/rec wired."},
    {:name => "Clarissa Notley", :notes => "Self catering neg. Use of study & TV/B'fast. O'looks g, Bus to King's Theatre"},
    {:name => "Colin Stone", :notes => "ph/fx/voicemail/internet, daily srvc/full kitchen, shwr&, 23 1,2,&3 bed apartments, Daily maid service"},
    {:name => "Audrey Jenkinson", :notes => "Fully fitted kitchen/ lounge/ very central"},
    {:name => "Beverley Cox", :notes => "Double room available in large flat sharing with one of the theatre's stage door keepers. This is a very central yet quiet location just a few mins. walk from the Edinburgh Playhouse. All attractions & amenities are very close by and both bus & train stations are less than 10 mins. away. Full GCH, 2 bathrooms, spacious & well equipped kitchen with dw, a large sitting room with Freeview & DVD...and a cat! Bed linen & towels are supplied. Non-smokers preferred. "},
    {:name => "Charlotte Hains", :notes => "Both rooms have TV, use of kit/sh/bath. Georgian flat close to all amenities, Buses to King's & Festival Theatres"},
    {:name => "Heather Muirhead", :notes => "3 Rms, 5 beds/shr. Rm. Newly refitted. Sit/Din/Kit/GCH/TV/DVD/awm/td/mw"},
    {:name => "Helen Evans/Andrew Fletcher", :notes => "TV/video/cable/ stereo/int access/ printer/CH, Bus to Festival Theatre"},
    {:name => "Isty Ahmad", :notes => "Newly furnished to high standrd. City Centre. Bus to King's Theatre"},
    {:name => "Jacqueline Steward", :notes => "Recep, din. Kitchen, bath, TV/DD/CD, 5 mins. Walk from Princes Street. Bus to King's Theatre"},
    {:name => "Jon ", :notes => "Bright double room available to let within 2 bedroom flat. 5 mins. walk from Playhouse Theatre/City Centre. Shared kitchen, bathroom & Living Room. Internet Access available 24 hrs in the Living Room. This is a Gay-friendly and smoke-friendly flat and we also have a small dog named Charlie. "},
    {:name => "Kathryn McDonald", :notes => "17th Century Farmhouse. Short or long term lodgings available. May, June, July. Own transport needed."},
    {:name => "Katie Kerr", :notes => "Lounge, dining area, luxury kitchen/bath, TV/DVD/CD/Balcony."},
    {:name => "Lorraine Thompson", :notes => "Fully serviced Apartments close to City Centre, new development at Haymarket. Furnished to high standard, fully fitted kitchen, ensuite, lounge/dining room, 2 bedrooms, free parking. No Smoking. "},
    {:name => "Louise Anger", :notes => "Bed linen and towels provided. "},
    {:name => "Mairi or Cathy", :notes => "2 dbls/Shower Rm/WC/Liv/Din/TV/DVD/CD/Fully Equipped Kit/No Smoking or Pets. Buses to Festival & King's Theatres. "},
    {:name => "Margaret Durkin", :notes => "Shower/Guest Toilet, Fitted kitchen/Swimming Pool/Gym/Sauna"},
    {:name => "Mike Rivington", :notes => "Lnge, kit+din'g rm (mid July-end A). TV/WM/FridgeFreeze/Ckr/Bathr'm"},
    {:name => "Miss A Paton", :notes => "TV, full equip kit with M/W, fr & elec hob, recent refu"},
    {:name => "Miss Playfair", :notes => "One double room, Male or Female. "},
    {:name => "Miss Rossi", :notes => "Shower/bath/kit/lounge. Breakfast prov. If required, smokers welcome. Large. Buses to King's & Festival Theatres"},
    {:name => "Mr & Mrs Birt", :notes => "Flat, short lease available for up to 6 months.Bedding etc can be made available. Gas CH. (one month's deposit). sofa bed in box room."},
    {:name => "Mr J Pringle", :notes => "Flat with 2 double beds with en-suite, cable TV/CH, all linen, pvt. Parking, Buses to King's & Festival Theatres"},
    {:name => "Mr J Pringle", :notes => "3 Double bed with ensuite flat, cable TV/CH,all linen, pvt.parking, Buses to King's & Festival Theatres"},
    {:name => "Mr McPake", :notes => "Flat, 3 bedrooms, CH & all new furnishings. "},
    {:name => "Mr McPake", :notes => "Flat, 4 bedrooms, 3 bathrooms, VERY close to theatres. All new furnishings. Superb views. "},
    {:name => "Mr R John Howden", :notes => "Single room & wardrobe space. CH, bed linen, towels, full use of kitchen facilities. Prefer non-smoker. Rent is payable in advance. Buses to Festival & King's Theatres."},
    {:name => "Mrs Barnet", :notes => "1x Double with En Suite, 1x without, Can offer 4 singles. Lounge/kit, bath, TV/Video (non-smoking), Buses to King's & Festival Theatres"},
    {:name => "Mrs Carol Liddell", :notes => "Flat. Two double bedrooms (one ensuite), sitting room, dining room, dining/kitchen, bathroom. Price inclusive of bills."},
    {:name => "Mrs J Mill", :notes => "TV, Very friendly. Buses to King's & Festival Theatres"},
    {:name => "Mrs Jackie Laird", :notes => "TV/WM/Fr.Freezer. Mod.res. Views Arthurs Seat, 3rd Floor Flat, Sofa bed is single chair bed. Bus to King's Theatre"},
    {:name => "Mrs Janice Laird", :notes => "Top floor flat, TV/WM/Fr.freez, leisure facs. Parking. Buses to King's & Festival Theatres"},
    {:name => "Mrs Janice Laird", :notes => "Sofa bed is double, Ground floor flat, TV/WM/Fr.Freez/M'wave, leisure facs. Enclosed patio, Buses to King's & Festival Theatres"},
    {:name => "Mrs Janice Laird", :notes => "1st Floor Flat. Linen/TV/WM/ff/mw/cooker. Buses to Festival & King's Theatres."},
    {:name => "Mrs Jess Mill", :notes => "All with own Amenities. Separate toilet & bathroom. "},
    {:name => "Mrs N Holmes", :notes => "Bath/Shr, TV in room Breakfast if required. Bus to Festival Theatre"},
    {:name => "Ms Gillian Mackenzie", :notes => "L'rm/TV.CD/kitchen/m'wave/b'room with showr. Via E.Fettes Ave/Inverleith/Broughton St/Via W.Winnelstrae/E.Fettes Ave./Q'fry Road/Lot"},
    {:name => "Ms Gillian Mackenzie", :notes => "Bathroom with shower/living rm/TV/video. Kit with apps/GCH/priv.park. Buses to King's & Festival Theatres"},
    {:name => "Ms Gillian Mackenzie", :notes => "Fully euip kitchen/br.com.lounge, GCH/TV"},
    {:name => "Nicola Burnett Smith", :notes => "WM/CH/DG"},
    {:name => "Pauline Duncan", :notes => "Buses to Festival & King's Theatres."},
    {:name => "Pauline Duncan", :notes => "Lnge/Din/Kit/Bath/Show/TV/Internet/wm/ff/dw/West End location 4*"},
    {:name => "R. John Howden", :notes => "Full use of kitchen/WM, Good bus routes"},
    {:name => "Ros Lambert", :notes => "Delightful & artistic 1 bedroom garden apartment situated within Grade A listed Georgian townhouse in the City Centre and a 10 min.walk to the Playhouse theatre. Set in Edinburgh's prettiest Georgian square, the flat has a large sitting room, double bedroom, kitchenette & shower room. Polished wooden floors throughout. Own front door entrance & pvt.patio with table & chairs for 'al fresco' eating. Wireless Broadband internet & Sky TV. Non-smoking and no pets."},
    {:name => "Ros Lambet", :notes => "Large sunny peaceful 1 bedroom flat 5 mins. walk from Playhouse Theatre. Stylish open plan kitchen/lounge, large double bedroom & bathroom with shower. Polished wooden floors & well decorated. Suitable for 2 people."},
    {:name => "Shona McLean", :notes => "TV/parking, non smokers/linen provided/cot. Bus Service to King's Theatre"},
    {:name => "Sue Lieberman", :notes => "One double, shared bathroom. No smoking/vegetarian, views, quiet near shops & restaurants"},
    {:name => "Vanessa Rawlings-Jackson", :notes => "bathroom with shower,sitting room,TV/Video/Stereo/Kit/WM,city centre loc"},
    {:name => "Vivienne Bell", :notes => "Use of all facilities. Rent of £100 pw is negotiable. "},
    {:name => "Yanne Robertson", :notes => "Apartment, 2 large bedrooms & single room. Fully equipped, comfortable, own front door. Spacious, heat, light, linen, towels supplied. Central."},
    {:name => "Alan & Louise Kay", :notes => "Single room in house. Use of kitchen etc. Bus to King's Theatre"},
    {:name => "Alastair Warr", :notes => "Bus to Festival Theatre. "},
    {:name => "Alison Linklater", :notes => "shared bathrm.&shr/sunny area with seats. Bus to Festival theatre & Kings theatre"},
    {:name => "Alistair Baker", :notes => "TV, quiet area close to shops, garden, Luxurious Double. Buses to King's & Festival Theatres"},
    {:name => "Anita Anderson", :notes => "Lounge/dining/bath/shower/kitchen, all mod cons. 3 rooms with TV. Buses to King's & Festival Theatres"},
    {:name => "Ann Giles", :notes => "TV in dbl, high standard of comfort"},
    {:name => "Anna Caro", :notes => "Two rooms (share sep. bath/shower), Wireless Access."},
    {:name => "Anne ", :notes => "Luxury Apartment. Nice Views, private parking. "},
    {:name => "Anne Long", :notes => "One double room & twin room for bed and breakfast. Use of kitchen by arrangement. Twin room has ensuite facilities & double room has private bathroom a few steps away. The house is decorated and furnished to a very high standard. Photos can be emailed if necessary. "},
    {:name => "Annie Pettigrew", :notes => "2 rooms, whb in both, good views. Offers Breakfast. "},
    {:name => "Avril Kunzel", :notes => "TV in room, large bath/show. Broadband, parking. Bus to Festival Theatre & City Centre."},
    {:name => "Brendan Garry", :notes => "TV/Video/CD/Views castle."},
    {:name => "Brid Cullen", :notes => "1 Room, Spacious flat, 2nd floor, TV. Bus to King's Theatre"},
    {:name => "Callum Gibson", :notes => "One double with ensuite, living/kit/Plasma TV/all Mod Cons/High Standard."},
    {:name => "Calum Mackinnon, Purple Cow Apartment", :notes => "TV/DVD,GCH, Hot Tub, Stair to Roof."},
    {:name => "Carol Ann Crawford", :notes => "Quiet/Cable TV/Broadband, fully equipped Kitchen. Park.Buses to Festival & King's Theatres"},
    {:name => "Carol Stevenson", :notes => "Shared bath/shower/TV in room/use of din/rm/kitchen. Stone Cottage. Buses to Festival & King's Theatres. "},
    {:name => "Catherine Germillac", :notes => "TV/Video"},
    {:name => "Catherine Weir", :notes => "Stylish self catering 1 bedroom apartment just minutes from the heart of the city and situated right behind The Playhouse Theatre. Just 5 mins. From Princes Street & Waverley Station and located close to a wide range of bars, restaurants & shops. You'll find everything you need right on the doorstep. Famous attractions such as Edinburgh Castle are within easy walking distance making this flat the ideal base for exploring the city.Towels & linen are provided. Car parking space can be arranged with prior notice. Strictly non-smoking & no pets are allowed. Additional Features:Cable/Satellite TV, DVD player, Wi-Fi Internet Access, fridge, mw, wm, iron & ironing board, hd."},
    {:name => "Cathy Miller", :notes => "Large newly decorated rooms, shared bathroom, fully equipped kitchen. "},
    {:name => "Catriona Joss", :notes => "TV/radio/cass. Use of Kit/wm. Owner is smoker + 2 cats. Buses to Festival & King's Theatres."},
    {:name => "Catriona Joss", :notes => "Bright & well furnished double room in privately owned 2nd floor flat. 5 mins. from Town Centre on bus. Frequent bus services to all areas of town during day & served by night buses.Room has colour TV, radio/cassette player & electric alarm clock. All linen provided. Unlimited access to sitting room, kitchen, bathroom & laundry facilities. B'fast provided. Owner is a smoker & has 2 cats."},
    {:name => "Catriona Osborne", :notes => "37 Apartments/ 1,2 & 3 bed/serviced daily. TV/DVD. Bus to King's Theatre"},
    {:name => "Christine Innes", :notes => "Lg. dbl rm (sleeps 1)/Wireless con. TV in room - can provide b'fast. Bus to Festival Theatre."},
    {:name => "Christine Povey", :notes => "One dbl (ensuite show), Use of Kitchen, Acc to Broadband, quiet. Buses to Festival & King's Theatres"},
    {:name => "Christine Sproull", :notes => "1 room (not ensuite), rec.dec.rm/quiet/use of kit/bath.TV. Buses to Festival & King's Theatres."},
    {:name => "Clare Buchan", :notes => "TV, high standard, quiet. Buses to Festival & King's Theatres"},
    {:name => "Craig Robertson", :notes => "Apartment, 3 dbls (1 ensuite) serviced daily. Lge lounge/b'fasting kitchen/quiet"},
    {:name => "D Jardine", :notes => "Shared bathroom, use of kitchen & living room. Towels & sheets supplied."},
    {:name => "David Campbell", :notes => "Spacious Single, No TV/Lge rms/good company or privacy, Buses to King's & Festival Theatres"},
    {:name => "David Gerrard", :notes => "Private Entrance/Sit Rm/Din/Kit, TV, garden, parking possible. "},
    {:name => "David Todd", :notes => "In Old Town, one room, shared bath. "},
    {:name => "David Watson", :notes => "1 single ground floor room with single bed, wardrobe & cupboard space, TV, CH, radiator & electric fan/fconvector heater. Access to shared ground floor kitchen for tea/coffee making and to adjacent shared bath/shower room. Breakfast of toast, cereal, fruit, etc. provided. The room is in a detached family home in a quiet street. We have 3 cats. Bus routes for services into City Centre & across town are close by. "},
    {:name => "Debbie Cameron", :notes => "Two rooms to let in house (top storey). The two rooms share shower & toilet. Use of kitchen & lounge. "},
    {:name => "Deborah Galbraith", :notes => "Self-contained superior flat within Georgian family home. Sleeps 2-4. Also single room in owner's flat. Bus to King's Theatre"},
    {:name => "Deborah Riley", :notes => "Single bedroom avail. within ground floor flat with garden,shared kitchen, bathroom, TV in sitting room. Buses to Festival & King's Theatres"},
    {:name => "Denise Marr", :notes => "TV/high standard/parking, Buses to King's & Festival Theatres"},
    {:name => "Derek McDonald", :notes => "Lounge with bed settee, bath with shower. Fully equiped kit/TV/VCR,GCH/linen/towels, Buses to King's & Festival Theatres"},
    {:name => "Desi Angus", :notes => "can provide breakfast TV,central quiet street,nr amenities. Bus to King's Theatre"},
    {:name => "Dr Graham D Bacon", :notes => "CH/large garden/lounge/conservatory/kitchen. Rural area."},
    {:name => "Dr R M Wrate", :notes => "dbl bedroom as sitting room, D'ng Kitchen, shr.rm. Sep WC; entry phone. Avail. 19th July. 20 mins walk over Meadows to King's Theatre"},
    {:name => "E Ewen", :notes => "Luxury Penthouse/balcony, priv.park/kit/din/lnge/ 5* rating. Buses to King's & Festival Theatres"},
    {:name => "Eddie Lamb", :notes => "Villa in quiet residential aea, 5 mins. by car to theatre. Bathroom, shower room, kitchen,utility room, GCH, DG, garden, street parking. P117 "},
    {:name => "Edna Glen Miller", :notes => "Use of TV/sitting rm/kitchen/garden. Buses to King's & Festival Theatres"},
    {:name => "Elaine Adams", :notes => "Situated just around the corner from Playhouse Theatre, 2 Hillside Crescent is a newly opened luxury B&B set in a beautifully restored Georgian Town House. Its relaxed welcoming atmosphere, central location and attention to detail make it an ideal place to stay whether your stay is for business or leisure. We believe the two most important things about a Bed & Breakfast are indeed the Bed and the Breakfast. That is why all our beds are equipped with luxury linen, goose down duvets & Vi Spring mattresses to guarantee a great night's sleep (doubles are at least king sized & over 6'6"" in length). Our delicious b'fast includes fresh seasonal fruit, homemade preserves & a choice of cooked b'fast using responsibly sourced local, organic & free-range produce. Each individually decorated bedroom has its own distinctive character complete with flatscreen TV, hd, tea & coffee.Arran Aromatics toiletries, free Wi-Fi & CD/DVDs available on request. "},
    {:name => "Elaine Allison", :notes => "Shared bath/shower, use of kit/din'rm, sit'rm, quiet, Vic. Crescent. Buses to King's & Festival Theatres"},
    {:name => "Eleanor Macdonald", :notes => "1 Flat with sit'rm/bedroom/bath/shower/kit. TV/video/Frid.Freez/WM/DW/3* Tourist Board, Buses to King's & Festival Theatres"},
    {:name => "Eleanor Milner", :notes => "A quiet double room is available in a lovely cottage alongside the Royal Botanic Gardens in leafy Inverleith, near Stockbridge. The cottage has been totally renovated & decorated to a very high standard, has its own front door, a very large kitchen, large sitting room with open gas fire, study with Internet access, 2 bedrooms (one for theatre digs use!) a bathroom with bath & shower & downstairs loo.There is a pretty shared garden with leafy green outlook. Very quiet location & free parking available at other end of street. Prefer no couples and non-smokers please.  Bed linen & towels will be provided. You are welcome to share the kitchen & living rooms as well as TV, CD player etc. Inverleith Place is very close to excellent bus routes into the City Centre - all stop less than 2 mins. away. Some/all of the buses go directly to or near the theatres"},
    {:name => "Elizabeth Cutting", :notes => "Facilities including bathroom, kitchen, garden & parking. Close to the sea and central (lots of buses into town- approx. 10 mins.)"},
    {:name => "Emma Vardy", :notes => "Private bath/Liv/Din/Kit/Cbl TV/Broadband/DVD/Priv Parking/no smoking. Buses to Festival & King's Theatres"},
    {:name => "Eric Robinson", :notes => "One single room with pvt. S'room. B'fast/quiet/well-furnished. Bus Service to Kings Theatre"},
    {:name => "Evelyn Smith", :notes => "Festival flat to let - one bedroom, recently redecorated & fully furnished in period style. Rent includes services but not telephone."},
    {:name => "Ewan Mathieson", :notes => "Self-contained flat with one double bedroom, spacious lounge, kitchen, recently refurbished. Short or longer term let. "},
    {:name => "Fiona & John Clifford", :notes => "Studio flat in Georgian family house, kit/bath/own door/phone/TV.non-smoking, Buses to King's & Festival Theatres"},
    {:name => "Fiona Bain", :notes => "Full use of kitchen/TV etc. Small dbl, Buses to King's & Festival Theatres"},
    {:name => "Fiona Forsyth", :notes => "One Self-contained flat (within house). Large rm/ensuite sh. Fitted kitchen. Buses to Festival & King's Theatres"},
    {:name => "Fiona Harkness", :notes => "One double access to Lounge/Kit/Bath. By the Sea/non-smoker/cat. Buses to Festival & King's Theatres. "},
    {:name => "Fiona Macalister", :notes => "2 rms (1 split level) (not ensuite). Sit rm. (Piano), Kit/Din/Bath/Show. Open views Castle/Bl. Bus to Festival Theatre"},
    {:name => "Fiona Stephens", :notes => "Open plan garden flat, sitting room (big sofa that can also be slept on), dining area (easy for 4, can sit 6 people at a squeeze), open kitchen (wd, dw, fridge, mw etc. Smart bathroom with shower over bath.2 bedrooms, good storage + desk, overlooking garden, nearby parking, fairly recently refurbished fully equipped, linen, iron, china, TV with freeview etc. Very close to Princes Street shopping centre, cinema, transport, bars, restaurants etc. Cleaner available if requested."},
    {:name => "Fiona Wood", :notes => "1 bed sitting room, vegetarian b'fast avail/bright/sunny/comfortable. Buses to Festival & King's Theatres"},
    {:name => "Fiorella Rossi (Fi for short!)", :notes => "Quietly located 1 bed apartment on Royal Mile, a short walk to Edinburgh Castle, Holyrood Palace & Park, Princes Street, Waverley Train Station, bus stops, bars, restaurants, theatres etc. 1 Double bedroom, shower room, open plan lounge/kitchen with sofa bed & dining table, TV, wm, mw, electric hob & oven, ff, kettle, cutlery & all utensils. Smoking is permitted & well behaved & neutered pets welcome. Electricity payable by long stay guests. Long Stay: linen changed & apartment cleaned once a week."},
    {:name => "Frances Williams", :notes => "1 dbl + 1 dbl sofa bed, newly refurbished. Good views. "},
    {:name => "Gary Scott", :notes => "newly refurb, central, CH, good views of castle"},
    {:name => "George Goldsmith", :notes => "Deluxe standard, centre of town"},
    {:name => "Gill Baird/Max Williamson", :notes => "Self-contained attic rooms with private bath"},
    {:name => "Gillian Charlton-Meyrick", :notes => "TV/b'fast/cof+tea fac. /no smkg/no food in b'rms"},
    {:name => "Gloria Landale", :notes => "One double bedroom (prefer 1 person). Use of all facilities in the house. "},
    {:name => "Grace Durham", :notes => "Twin room with whb, shower room opposite, TV 1st FL.FL overlook gardens N/A 27 May-7July, 30July-3"},
    {:name => "Graham Raith", :notes => "1x single with ensuite, 1x dbl with ensuite"},
    {:name => "Greg McMillan", :notes => "Modern flat in residential area. 1 dbl (ensuite) Breakfast included. Buses to Festival & King's Theatres."},
    {:name => "Guri Le Riche", :notes => "TV/kettle/Bath/WM/Fridge/Ckr/shared pub.rms. Bus to Festival Theatre"},
    {:name => "H Speirs", :notes => "1 dble bed/sofabed in lounge. Lux. Kit/Bath/Views/Quiet/Parking."},
    {:name => "Helen Bates", :notes => "Spacious double room available on bus routes. No Smoking. "},
    {:name => "Helen Morgan & Sally Wainwright", :notes => "Lge dbl rom/TV/Radio in rm. Use of kitchen/women only/9 yr. old child. Bus to Festival Theatre"},
    {:name => "Helen Redmond-Cooper", :notes => "Full Use of Amenities. "},
    {:name => "Helen Sutherland", :notes => "One bedroom in a 2 bedroomed flat. Use of kitchen, living room etc. "},
    {:name => "Helena Scott", :notes => "TV/Kit/Toilet,Shower-room/WHB/non-smk, quiet, cen. Bus to Festival Theatre"},
    {:name => "Iona Macleod", :notes => "Large sitting/din. Internet Access. Quiet. Bus to Festival Theatre."},
    {:name => "Irene Allan", :notes => "One large dble/TV/extra sofa bed/Views over City. Buses to Festival & King's Theatres. "},
    {:name => "J Hutchinson", :notes => "Kit/Bath/Lounge with Pno/CH/no smoking, Buses to King's & Festival Theatres 1 sofa bed In Lounge"},
    {:name => "J Robertson", :notes => "Lge Kit/SitRm/Util/TV/Video/WM/Dish/Fr.Freezer, 5* flat with 3 rooms, own door. Bus to King's Theatre"},
    {:name => "Jacquie Martinez", :notes => "Single room 5 mins. walk from Playhouse Theatre in family home. Available for short or long term let. Accommodation comprises of single bed, chest of drawers, wardrobe, table, chair, TV, coffee/tea facilities, wireless Internet. CH. South facing onto garden. All bills included."},
    {:name => "James Donald", :notes => "Meat-free breakfasts & special diets catered for. Close to stations. Sumptuously decorated. "},
    {:name => "Jamie Bowes", :notes => "New Flat/TV/DVD/WM/DW, all mod cons. Bus to King's Theatre"},
    {:name => "Jan Sutherland", :notes => "Lnge has Sky/Broadband/high standard. Bathroom/equipped kitchen"},
    {:name => "Jane Garden", :notes => "2 Large singles with bath/shower (private). Pvt. Lge with TV/large house/beau gdn/ 2 x dogs. Bus to Festival Theatre. "},
    {:name => "Jane Jones", :notes => "3 gd/sized attic rms/TV/whb/adj shr/toilet. Access to kitchen. "},
    {:name => "Jane Miller", :notes => "Full Use of all Amenities. "},
    {:name => "Jane Miller", :notes => "Modern flat close to bars/rest. at the Shore. Use of all other rooms in flat. Buses to Festival & King's Theatres."},
    {:name => "Janet Kirkwood", :notes => "Dining Kit/Lounge/Bathroom/all mod cons. Bus to Festival Theatre"},
    {:name => "Janet Martindale", :notes => "Use of all facilities in flat. Buses to King's & Festival Theatres"},
    {:name => "Jean-Baptiste Richon", :notes => "Sm.rm., quiet. Living-Rm. TV/WM/Sh & bath. B'fast. Bus to Festival Theatre"},
    {:name => "Jeanette McRae", :notes => "Large Double  "},
    {:name => "Jenny Haslem", :notes => "use of kit/living/no smok/fam house, beaut views"},
    {:name => "Jenny McIntosh", :notes => "One bedroom flat. Price includes Council tax, bills & cleaner who sorts bed linen/towels. (No phone line) Not available during Festival. "},
    {:name => "Jim Mcqueen", :notes => "One Room but can be let as whole house"},
    {:name => "Joan Battersby", :notes => "Dinner Available if required. Buses to Theatres. "},
    {:name => "Joan Reid", :notes => "Beautiful flat, quiet, avail. till 13 December, Buses to King's & Festival Theatres"},
    {:name => "John Ramage", :notes => "1 dbl. plus boxrm/kit/bath/lnge/TV/DVD/Spectacular views"},
    {:name => "John Simpson", :notes => "First Floor Flat. Large dbl.bedroom with built-in wardrobe. Large sunny drawing room with sofa bed & dining area, seats 8. Well equipped kitchen with wm, cooker etc. Bathroom with electric shower & bath. White meter CH. Suit single person or couple. Free parking. Central, convenient location within walking distance of town, Botanic Gardens, good bus route. "},
    {:name => "Joyce Stobbart", :notes => "Double room to let in semi-detached house. On street, free parking, bed linen & towels provided.Non-smoker preferred. "},
    {:name => "Judith Sim", :notes => "TV/tea/coffee fac in room, quiet & comfortable. Bus to Festival Theatre"},
    {:name => "Julie Reynolds", :notes => "3 Bedrooms, living room, separate kitchen, dining room, CH. Rossie Place (along London Road)"},
    {:name => "Kaimes (Mrs K.Khader)", :notes => "Offer evening meals on request"},
    {:name => "Kate Wylie", :notes => "1 Large room/sngl. bed/TV/Sofa, Sh/WC, very comfortable. Buses to Festival & King's Theatres"},
    {:name => "Katie Kerr", :notes => "4 dbls. Lge lounge/DVD/TV/CD. Bath/show/kit/dw/mw/w/dryer. Great Views.  Bus to King's Theatre"},
    {:name => "Katriona Murray", :notes => "All facilities, CH, off street parking. Pleasant, quiet, cheerful. "},
    {:name => "Keith Paterson", :notes => "1 dble (King)/TV/DVD/Video/CD/Ipod Dock, Kit/wm/td/ff/mw,dw Bath/sh. Owner works away more often than not so you have the flat to yourself. Non-Smoking. Buses to Festival & Kings's Theatres."},
    {:name => "Kevin & Andrea Parsons", :notes => "Tea&coff facs./TV/some rms WHB"},
    {:name => "Kirsty Hutton", :notes => "Luxury Flat. Use of all facilities. Close to theatre"},
    {:name => "Kirsty Walker", :notes => "TV/VCR/CH/free parking, phoneline. Sofa bed in living room. Buses to King's & Festival Theatres"},
    {:name => "Kyrsta MacDonald", :notes => "Dbl with En suite, Modern décor (cable/broadband/internet) parking, Bus to Festival Theatre"},
    {:name => "L M Roberts", :notes => "Cable TV/WM/ beautiful views, close to amenities, Buses to King's & Festival Theatres"},
    {:name => "Lara Green", :notes => "Desk/GCH/shared kit/bath/LR/Wireless Broadband, Spare Mattress (if required) Bus to Festival Theatre"},
    {:name => "Laura Hamilton", :notes => "1 Double in 3 bed cottage, TV/Video. Share house NS/females only. Parking. Buses to King's & Festival Theatres"},
    {:name => "Linday Hendry", :notes => "Single is Fold Down bed, Lounge, galley kitchen/bathr'm/WC/GCH/AWM/TC/m'wave/Fr.F. Buses to King's & Festival Theatres"},
    {:name => "Lisa Grindall", :notes => "Two bedroom flat. "},
    {:name => "Liz Byrne", :notes => "Garden Flat 4*, sleeps 6, Kit/Lnge/TV/Video 1x dbl, 1x fam (dble+sgl),both ensuite. Bus to Festival Theatre"},
    {:name => "Lorraine Burns", :notes => "Bedsit, double glazing, CH, shower & bath. Use of kitchen, washing machine etc. Good bus service. "},
    {:name => "Lorraine Edwards", :notes => "Two Rooms, b'fast available. Modern/TV in room, shared Show/rm, Kitchen etc. Buses to Festival & King's Theatres"},
    {:name => "Louise Olly", :notes => "Clean, comfortable/TV/Video/Share Kit/Bath, Garden, near shops.Buses to Festival & King's Theatres"},
    {:name => "Malcolm Warrick (Address of accommodation)", :notes => "5 Flats, All flats have sofa bed in lounge too. Baths and Showers, parking. "},
    {:name => "Margaret McIntyre", :notes => "1 double or Double Box Room, Use of liv.rm, kit/din, bath/showr'm, ground fl. Buses to King's & Festival Theatres"},
    {:name => "Maria Bechaalani", :notes => "Box room in spacious non-smoking lower Villa just off the links. Share with owner (has two cats). Frequent bus service to City Centre/TV/GCH/bathroom with shower. Wi-Fi, bed linen & towels provided. On street parking. Personal phone calls priced separately. Owner works in theatre/events. "},
    {:name => "Marianne Everett", :notes => "1 Double ensuite, TV/Priv.Bathrm/B'fast if required/quiet, Bus to King's Theatre"},
    {:name => "Marilyn Nicholl", :notes => "Victorian Terrace House, Self catering or B&B (flexible). No smoking. "},
    {:name => "Marisa Carradice", :notes => "Bruntsfield situated flat. Large fully furnished, 1 large bedroom, 1 box room. Garden to rear of property"},
    {:name => "Mark Kydd", :notes => "GCH/TV. Welcoming, good views. Buses to King's & Festival Theatres"},
    {:name => "Marnie Roadburg", :notes => "Large Single bed, Lge rm/patio & garden/breakfast/quiet/central, 5 mins by bus to Kings Theatre"},
    {:name => "Mary Cowan", :notes => "Shower Room off Kit. Non-Smoker. Terrace House. Bus to Festival Theatre. "},
    {:name => "Mary Taylor", :notes => "Lounge/ dining area/ kit/ TV/ video/ m'wave/ linen/ bat"},
    {:name => "Maureen Coia", :notes => "kitchen,ensuite bathrooms/TV/CD,Ph/direct dial, café, Bus to King's Theatre"},
    {:name => "Maureen McDonald", :notes => "Large Single - use of shower/bath, TV, use of kit, laundry at no charge, n/smoking, b'fast £1.50. Buses to Festival & King's Theatres"},
    {:name => "Melanie Adam", :notes => "TV/T&C.facilities/Payphone. There are cats. Non-smoker preferred. On bus route."},
    {:name => "Michael Young", :notes => "Stunning 2 bedroom main door Georgian property over two floors situated on eastern edge of New Town opposite Playhouse Theatre. Total period restoration recently completed. Comprises: large entrance hall leading on to larger circular reception hall, very large lounge, hi spec split level dining kitchen, top spec. bathroom with power shower. Furnishings, decor, fixtures & fittings are of the highest standard. Available for long or short let. Pictures available upon request. "},
    {:name => "Mima Scott", :notes => "Self contained Mews Cottage, 3 bedrooms, living room, kitchen, bathroom, fully furnished. Just opposite Playhouse. Phone extra on top of rent."},
    {:name => "Miss E A Chirderley", :notes => "All Facilities. Garden"},
    {:name => "Miss Joanna Ortowska", :notes => "Single £15 pnpp, £24 pp for 2 people.Rooms have colour TV, tea/coffee facility. Bed linen etc. "},
    {:name => "Miss L Miller", :notes => "CH/TV/use of bath/shower room, B&B if required. 2 dbls or 1 with 2 singles if required. Buses to Theatres"},
    {:name => "Miss McManus/Mr Munro", :notes => "TV/DVD.GCH/new fixtures/no smoking"},
    {:name => "Mr & Mrs Alexander", :notes => "SS Grnd floor cottage/flat. Buses to King's & Festival Theatres"},
    {:name => "Mr Aziz Tigani", :notes => "Double room with TV to let in 1st floor central flat, approx. 15-20 mins. walk from theatre. CH, well equipped kitchen & bathroom with shower. Non-smoker preferred."},
    {:name => "Mr Hepburn", :notes => "Various Accommodation"},
    {:name => "Mrs Audrey Mitchell", :notes => "Gas, Electricity, house tax - phone not included"},
    {:name => "Mrs Brydon", :notes => "SC Flats (studios to 2 bedroom flats). TV/WM/M'wave. Pvt. Parking may be available. Buses to Festival & King's Theatres."},
    {:name => "Mrs Caroline Reeve", :notes => "Use of Digital TV in lounge/CH/bathroom/WM/M'wav"},
    {:name => "Mrs Case", :notes => "Kitchen, lounge, bathroom, GCH, fully furnished, dishwasher."},
    {:name => "Mrs Cecilia Leishman", :notes => "Bed & Breakfast, Single, Twin & Doubles. All ensuite rooms with TVs, tea & coffee 4*"},
    {:name => "Mrs Couper (Address of accommodation)", :notes => "Ground floor 2 bed flat. Lounge, kitchen, box room, bathroom, fully furnished. Gas fires. Sleeps 4-6 people"},
    {:name => "Mrs Criper", :notes => "2 dbl (1 ensuite) TV/Small Fridge/bed linen prov/Use of Kitchenette. Bus to King's Theatre"},
    {:name => "Mrs D A McKay", :notes => "Bills/laundry/tea & coffee facilities all inclusive. Single room £65.00 pw. Buses to Festival & King's Theatres."},
    {:name => "Mrs F Shaw", :notes => "TV/Internet acc/high stand/family home. Buses to Festival & King's Theatres. "},
    {:name => "Mrs Haldane", :notes => "All facilities. (Could accommodate 4)"},
    {:name => "Mrs J Hufstetler", :notes => "Top flat in York Place, 5 bedrooms, sitting room, dining room, 2 kitchens & 2 bathrooms"},
    {:name => "Mrs M Hynd", :notes => "Flat suitable for 2 occupants recently newly refurbished. Price includes electricity, bedding etc. "},
    {:name => "Mrs McIver", :notes => "1 double with en suite & 1 single (double bed). Continental b'fast/share sitt'g rm. Buses to King's & Festival Theatres"},
    {:name => "Mrs Priscilla Heaton-Armstrong", :notes => "16th Century House, very comfortable. 2 double bedrooms with use of study. Have own bathrooms. Use of kitchen facilities & td & wm. Smoking allowed. Garden & communal courtyard. Fax & Broadband available. "},
    {:name => "Mrs Rooney", :notes => "En-suite facilities in all rooms. Awarded 3 crowns by Scottish Tourist Board. "},
    {:name => "Mrs Rosemary Robertson", :notes => "TV, piano, elegant victorian flat ,plus cont bkfst"},
    {:name => "Mrs S V Broughton", :notes => "Bath/Shr/CH/share TV/B'fast. Views.High std. Bus to Festival Theatre"},
    {:name => "Mrs Sherman", :notes => "TB/No smoking/No pets - quiet residential area. Buses to King's & Festival Theatres"},
    {:name => "Mrs Thompson", :notes => "Gr. Fl. Flat - Two dbl, liv/kit/Sh/WC/TV/wm/shared garden/Good Standard. Buses to Festival & King's Theatres. "},
    {:name => "Mrs Vanessa Henderson", :notes => "1 large twin room, shower rm next door/TV/Use of Kitchen/Bright sunny south facing."},
    {:name => "Mrs Watson", :notes => "4-5 bedrooms, lrg lounge, 2 bthrms, kit"},
    {:name => "Natalie Duffy", :notes => "Flat comprises of 5 double bedrooms, kitchen, toilet, bathroom & open hallway. It is an ideal location, opposite the Playhouse and 2 min. walk to Princes Street."},
    {:name => "Nicky De La Pena", :notes => "1 Single bright sunny room (possibly suit 2 singles), furnished with antique furniture. Study room available if required. "},
    {:name => "Nora Rogers", :notes => "Quiet room/shower/bath,2 WC's shared"},
    {:name => "Pat & Donald Carmichael", :notes => "Double with pvt. bathroom, tea/coffee fac. in room, no smoking, Buses to King's & Festival Theatres"},
    {:name => "Patricia Kane", :notes => "Two large rooms with whb, Bathroom, TV, Lounge, large garden. Buses to Festival & King's Theatres. "},
    {:name => "Pete Lyburn", :notes => "Third Floor Top Floor flat, 3 bedrooms, bath/shower, large living room & breakfast, kitchen, fully fitted with mod cons inc. dw. No Pets."},
    {:name => "Philip Gregory", :notes => "Beautiful three bedroom flat with two bathrooms in a new development just off Leith Walk. Large kitchen & separate sitting room with sofa bed. Broadband internet. Storage space. Flat features a secure underground parking garage, concierge service & private gym for the development. Double BR has ensuite shower room, 2 single BRs have shared bathroom/shower. GCH, wm,td, dw, mw, TV. Broadband & Sky. Linen & towels provided. "},
    {:name => "Pilla Scott Moncrieff", :notes => "Private bath/shower, MW/Kettle, lge house, high standard/no smoking, Bus to Festival & Kings Theatres"},
    {:name => "Quintus Farrell", :notes => "Large Double bed, Breakfast on request, high standard, use of flat, Bus to Kings Theatre"},
    {:name => "Rachel Brown", :notes => "TV/DVD, use of Kit/Bath/Broadband. Buses to Festival & King's Theatres. "},
    {:name => "Rebecca Preston", :notes => "1 Large room,  1 smaller room. Price Incl. of bills except telephone. Access to kitchen, front room, washing machine."},
    {:name => "Riccardo Gallo", :notes => "Bathroom,kit/TV/shower/newly renovated - high standard. Buses to King's & Festival Theatres"},
    {:name => "Robert Gillan", :notes => "1 Double room with private bath'rm, coal & gas fire + TV. Other shared facilities with owner. Attractive accommodation. Easy travelling distance to theatre. Bus to King's Theatre"},
    {:name => "Robert Jenkins", :notes => "TV/Video, parking,garden,quiet, views"},
    {:name => "Robert Scott", :notes => "Double room to let in well decorated & equipped terraced house. Shared bathroom & kitchen, sunny garden. On street, free parking. Bed linen & towels provided. The house is in the Meadowbank area of the city, half a mile from the Scottish Parliament and about 10 mins. on bus to both the Playhouse & City Centre. "},
    {:name => "Rosalinda D'Agostino", :notes => "TV, Kit/bathroom with bath. high standard, central"},
    {:name => "Rose Fleming", :notes => "Rooms with private shower rooms. Use of kitchen negotiable. 5 mins. walk from Holyrood Palace, Playhouse 15. mins. "},
    {:name => "Rose Johnston", :notes => "Self contained flat to sleep 2, ensuite, shr.room. Newly refurbished. Buses to King's & Festival Theatres"},
    {:name => "Ross Cooper", :notes => "Basement Flat/one small rm. /shared Show. Rm/Kit, very friendly. Buses to Festival & King's Theatres. "},
    {:name => "Ruth", :notes => "Luxury Bed & Breakfast accommodation (4*) recently refurbished to a very high standard single, twin & double rooms all ensuite with TV's & tea & coffee making facilities. "},
    {:name => "Ruth Callan", :notes => "1 Sgle, shared bath, simple room with views, can provide b'fast. Children & cats. Buses to King's & Festival Theatres."},
    {:name => "Ruth Logie", :notes => "Single bed is large, Sgle-self-catering (private digs)dbl-use of Liv/rm/Kit"},
    {:name => "Sandra Stalker", :notes => "1 sing. (ensuite) Luxury Pent/TV Fridge/kettle for tea/coffee drinks. Open outlook to river, leafy park, private parking. Lift access.. Buses to Festival & King's Theatres. Rates negotiable."},
    {:name => "Sarah Paterson", :notes => "TV, Georgian Garden flat, quiet, laid back hosts, (breakfast available) Buses to King's & Festival Theatres"},
    {:name => "Sarhan Rahman", :notes => "Top floor, two bedroom flat, kit, utility room, spacious sit room, double b'rm, sgl b'rm. Buses to King's & Festival Theatres"},
    {:name => "Scott Gowans", :notes => "TV, Video, tel. GCH.good standard of comfort, 3 bedroom flat with 1 en-suite, large lounge, bath, DVD"},
    {:name => "Shameen Mohammed", :notes => "Newly decorated, modern kit/new bath, TV/DVD/private parking/linen provided."},
    {:name => "Sharon Adams", :notes => "Shared use of bathroom, use of kitchen, TV/tea/coffee making facilities. Good area with restaurants/shops."},
    {:name => "Sheila McGlashan", :notes => "1 bedroom flat for up to 2 people living area, separate kitchen. VERY close to theatre. Bus to King's Theatre"},
    {:name => "Shona Irvine", :notes => "Single room, modern conveniences, normal facilities, CH. "},
    {:name => "Simon Miller", :notes => "Shared use of kitchen/living area. Bus to Festival Theatre"},
    {:name => "Simon or Ashley", :notes => "2nd Floor Festival Flat to let. Sunny, central, free parking. 1 min. walk from East London Street."},
    {:name => "Stephen Penman or Marion Buchanan", :notes => "2 Double Bedrooms available, use of garage, garden, kitchen, lounge etc. "},
    {:name => "Steve Stewart", :notes => "Shower/TV/DVD/HiFi/WM/Dryer/Dishwasher/MW"},
    {:name => "Sue Tait", :notes => "Shower for all rooms/TV/Use of House/Quiet/Comfy/Views/B'fast available. Buses to King's & Festival Theatres."},
    {:name => "Susan Collin", :notes => "Single furnished room to let, CH, shared bathroom & sitting room. B&B available"},
    {:name => "Susan Hainsworth", :notes => "1 Lge dbl with living room space. Sharing Liv/Din/Bath/show. All mod cons./high standard."},
    {:name => "Susan Mercer", :notes => "Clr.TV, tea/coffee in room. Full use of kitchen. Cont. b'fast if required. Good bus route. Buses to Festival & King's Theatres."},
    {:name => "Susie Dumbreck", :notes => "Large dbl room in sunny two bed flat, mins from Playhouse Theatre & Princes Street. (Also close to Edinburgh Festival Theatre & short bus ride to King's Theatre). Lovely room equipped with kingsize bed, TV/DVD Combo portable & good storage. Bedding, linen & towels provided. Full use of kitchen & wm. Large lounge with dining table (TV,DVD & Cable) and bathroom. No Smoking. Flat owned by former WE performer."},
    {:name => "Suzi Dumbreck", :notes => "Studio Flat/Dbl. platform bed/lounge area beneath/kit & dining area. Buses to King's & Festival Theatres"},
    {:name => "Thomas Muldownie", :notes => "Lounge, kit, bathroom. B'fast or SC negotiable. Compact & comfortable. Buses to Festival & King's Theatres."},
    {:name => "Trish O'Neil", :notes => "Large room for 1 or 2 people just across the road from theatre. Use of kitchen & bathroom. CH. No telephone. "},
    {:name => "Trish Sully", :notes => "Single room in 3 bedroom flat. All facilities. "},
    {:name => "V Crawley", :notes => "1x Dbl with en-suite/shower, Dig. Radio,Tea/Coffee making, non-smoking, shared bathroom. Bus to King's Theatre"},
    {:name => "Vanessa Grieve", :notes => "TV/CH/Con.Breakfast provided @ £3.00 pd, Buses to King's & Festival Theatres"},
    {:name => "Vanessa Habib", :notes => "1 studio in garden with 2 sgl beds. Lge rm, priv bath, CH/TV/Comp Term./Tea/coffee fac. Buses to King's & Festival Theatres"},
    {:name => "Vanessa Healey", :notes => "Rooms to let & 1-3 bed apartments. Includes linen, towels/CH/HW/Elec.laundry fac.  Buses to King's & Festival Theatres"},
    {:name => "Vanessa Henderson", :notes => "1 large dble/shared bathroom, lge. Sit/Rm/ Lge Kit, fully equipped/nice view.Buses to Festival & King's Theatres. "},
    {:name => "Veronica Robertson", :notes => "use of din/rm/bath/kit (rest of flat is private), Bus to Festival Theatre"},
    {:name => "Vicky Wynn", :notes => "Lounge, use of kitchen."},
    {:name => "Wendy Mathison", :notes => "Twin or Dbl"},
    {:name => "Wendy Robertson", :notes => "Lovely accommodation in dbl rm in quiet basement flat 2 mins. from Playhouse.Cosy dbl b'room in welcoming traditional Georgian flat shared with owner. New bathroom, outdoor area suitable for smokers, use of sitting room - open fire in winter months. Tea/coffe making facilities. Self catering or half board available. 5min. cab ride/10 min.walk to Edinburgh Waverley railway station situated off village-like Broughton Street which is home to wonderful independent restaurants, cafes, shops & bars. Quiet little park at nearby Gayfield Square offers space to exercise."},
    {:name => "Wendy Todd", :notes => "1 Large dbl. lge, living room, dining/kitchen, TV,DVD/shower room, Broadband.Fully refurbished."},
    {:name => "Alasdair Macdonald", :notes => "(Short term)  Sharing all Amenities"},
    {:name => "Andrea Kuypers", :notes => "Flat in Central Edinburgh. Equipped kitchen, Castle view, restaurants, supermarket. Buses to King's & Festival Theatres."},
    {:name => "Andrew Reid (Address of accommodation)", :notes => "One single room in a flat, bath & shower, free parking. Prefer a non-smoker. Male or Female."},
    {:name => "Anna Stevens", :notes => "Very central in Edinburgh's Georgian New Town. Quiet residential street. 5-10 mins.walk to Playhouse theatre. 2-5 mins. walk from bus stops & Tesco. Train & bus stations & airport bus 10 mins. walk. Within easy reach of Edinburgh's tourist & cultural attractions. Free street parking may be found a few mins. walk away. "},
    {:name => "Anna Stevens", :notes => "Spacious room, quiet - use of kit, bath with shower. Bus to King's Theatre"},
    {:name => "Anne Campbell", :notes => "Royal Mile, Sitting Room, Kit, Bath, GCH"},
    {:name => "Becky Duncan", :notes => "basic bkfst can be prov, non/smok. Bus to Festival Theatre"},
    {:name => "Carol Holder", :notes => "Large Single Bed, Views of wooden glen, pets, Buses to King's & Festival Theatres"},
    {:name => "Catherine Weir", :notes => "Stylish self catering 1 bedroom apartment that is just minutes from the heart of the City and situated right behind The Playhouse Theatre. Just 5 mins. from Princes Street & Waverley Station and located close to a wide range of bars, restaurants & shops. You'll find everything you need right on the doorstep. Famous attractions such as Edinburgh Castle are within easy walking distance, making this flat the ideal base for exploring the city. Towels & linen are provided. Car parking space can be arranged with prior notice. Strictly non-smoking and no pets are allowed. Additional Features: Cable/Satellite TV/DVD player, Wi-Fi Internet Access, fridge, mw, wm, iron & ironing board. hd."},
    {:name => "Colin Beck", :notes => "Large Victorian House, full use of all amenities, very well furnished/decorated"},
    {:name => "Colin I Beck", :notes => "B'fast or SC as preferred, very comfortable. Buses to King's & Festival Theatres"},
    {:name => "David Todd", :notes => "Lrg lounge, share dining hall, kit,bathroom TV/Video/M'wave/FF/Tel/linen/Bath/show - luxurious Cleaner twice weekly."},
    {:name => "Eddie Lamb", :notes => "Central flat within modern development, 5 mins. by car to theatre. 3 bedrooms, lounge/dining area, well equipped kitchen, bathroom, garage. "},
    {:name => "Eleanor Milner", :notes => "A quiet double room is available in a lovely cottage alongside the Royal Botanic Gardens in leafy Inverleith, near Stockbridge. The cottage has been totally renovated and decorated to a very high standard, has its own front door, a very large kitchen, large sitting room with open gas fire, study with Internet access, 2 bedrooms (one for theatre digs use!), a bathroom with bath and shower and downstairs loo.  There is a pretty shared garden and a leafy green outlook.  Very quiet location and free parking available at other end of street.  Prefer no couples and non-smokers please. Bed linen and towels will be provided. You are welcome to share the kitchen and living rooms as well as TV, CD player etc.},
    {:name => Location – Inverleith Place is very close to excellent bus routes into the city centre – numbers 8, 17, 23 & 27 all stop less than 2 mins away.   Some / all of these buses go directly to (or near) the Lyceum, Festival Theatre, Usher Hall, Kings Theatre, The Playhouse etc.   },
    {:name => Rent £90 per week in advance. For more pictures, please look website.  Buses to Festival & King's Theatres. "},
    {:name => "Elm View (James Donald)", :notes => " Meat-free b'fasts & special diets catered for. Close to stations. Sumptuously decorated. Bus to King's Theatre"},
    {:name => "Helen Tyrell", :notes => "Weekly price includes breakfast. Use of rest of the flat. Non-smokers only. "},
    {:name => "Jane McStay", :notes => "Self contained bed/sitting room (sleep 2 double. TV/CH/Fridge/Hairdryer/Iron/comfortable, Bus to King's Theatre"},
    {:name => "Jane McStay", :notes => "Small self-contained flat, shower & toilet leading off dining area, kitchen, CH. "},
    {:name => "Jeremy Neville", :notes => "One large double (ensuite bath)/TV/com.settee, large window/views/well appointed.. Buses to Festival & King's Theatres.  "},
    {:name => "Marilyn Nicholl", :notes => "Has 2-3 rooms to let. Can do B&B or Newington, Edinburgh self catering - it is flexible. (Victorian Terraced house) No Smoking"},
    {:name => "Miss Anderson", :notes => "Flat, lounge with dining area, bathroom, bath & shower, kitchen with mod cons. Off-street parking, gas CH. "},
    {:name => "Miss Boyes", :notes => "high standard of comfort, views to Castle, TV/shower/bath - not ens"}
    ]
  end
end
